### PR TITLE
Bubbles example

### PR DESCRIPTION
**Pull request by lokesh-krishna**
Is this okay? I've never configured in a lua file so not sure if I got it right.

### CODE REVIEW

**Comment by shadmansaleh** [comment]
I've fixed the lint issues and removed some stuff that you can relay one the defaults . You can check if you're fine with these changes .

Also what theme are you using ? moonfly doesn't look like the screenshot ?

**Comment by lokesh-krishna** [comment]
Thanks for the fix :) 
I'm using my own fork of moonfly. I've mentioned it as a comment in the example file.

**Comment by shadmansaleh** [comment]
> Thanks for the fix :)
I'm using my own fork of moonfly. I've mentioned it as a comment in the example file

Can you share the theme ?

**Comment by lokesh-krishna** [comment]
My bad, that was in a previous version. Should I add a mention so that people don't get confused? My fork is at [moonfly.nvim](https://github.com/lokesh-krishna/moonfly.nvim).

**Comment by shadmansaleh** [comment]
Ok thanks . I'll attach the theme with the example

**Comment by shadmansaleh** [comment]
I've added the theme along with example . I think we can merge at this stage . Do you have anything else to do ?

**Comment by lokesh-krishna** [comment]
A-OK from me! :D

**Comment by shadmansaleh** [comment]
Thanks for your contribution :)

**Comment by lokesh-krishna** [comment]
Honoured :)

**Pull request merged**
