### PR TITLE
Refactor: simplify options

### PR DESCRIPTION
**Pull request by shadmansaleh**
### Todo:
 - [x] **Deprecate upper & lower options**
These does not make much sense and `format=string.lower/upper` can provide same results
- [x] **Unify padding, left_padding, right_padding** 
I'll make it so if you pass a number it'll be used for padding both sides . and you can specify each padding with something like `padding = { left = 5, right = 2 }`. I'm thinking `padding = {left=5}` will only add padding to left and 0 padding to right . The global default will be `padding=1`.
- [x] **Make separators use left/right keys to specify left right instead of sequence**
Even I can't remember which one is left which one is right . So we will just make left = left_sep, right = right_sep. This applies to `component_separators`, `sections_separators` global options and `separator` local option . So you'll be having `component_separators = {left = '>', right = '<'}` instead of `component_separators = {'>', '<'}`
- [x] **Rename some options?:**
I feel like shorter names will be better you won't need
to write long options that you can't remember anyway .
     - [x] format -> fmt
     - [x] condition -> cond
     - [x] filetype:
         - [x] disable_text -> icon_only
     - [x] diagnostics:
       - [x] unify color_error,warn,info,hint in single option
           maybe like diagnostic_color = {error=..,warn=..,....}
     - [x] diff:
        - [x] unify color_added,removed,modified in single option
           maybe like diff_color = {added=..,removed=..,....}

This will soft break everyones config . Since we have decent notices now hopefully no one will feel a hit 😉 . Though this will just deprecate the old stuff with notices . Complete removal will happen later sometime like #4 / #11

This pr is open if you've any opinions regarding this please share . Or feel like some other parts of config can be made better with a bit of breaking change share the proposal here to . We can drop everything together at once.

### CODE REVIEW

**Comment by shadmansaleh** [comment]
I think I'll just make these changes in this pr .

Any one can try this out in this state . Most likely this is what's getting merged .

@chaeing @abzcoding Heads up breaking changes to config.

**Comment by chaesngmin** [comment]
Thanks for the work and the ping :+1: 

I think I am a bit late but if I may, I also prefer more explicit names too.

**Comment by shadmansaleh** [comment]
Only shorts that happened were:
- format -> fmt
- condition -> cond

separator -> sep & source/s -> src were dropped and instead of l/r left/right is used .

I think this is acceptable?

**Comment by Shatur** [comment]
> Only shorts that happened were:

I liked the way it was done before, but I can live with it :)

**Pull request merged**
