### PR TITLE
add folke/tokyonight theme for lualine

### PR DESCRIPTION
**Pull request by abzcoding**
what the title says 😅

### CODE REVIEW

**Comment by shadmansaleh** [comment]
tokyonight already provided lualine theme https://github.com/folke/tokyonight.nvim/blob/main/lua/lualine/themes/tokyonight.lua . Why does this need to be in this repo ?

**Comment by abzcoding** [comment]
with the recent commits it doesn't work, not sure if sth needs to be changed in tokyonight repo or what
i have this in my config
```lua
  local name = vim.g.colors_name or ""
  local ok, _ = pcall(require, "lualine.themes." .. name)
  if ok then
    config.options.theme = name
  end
  require("lualine").setup(config)
```
it was working properly until recent commits, but currently i get this error
Screen Shot 2021-09-19 at 11 24 16 AM
Screen Shot 2021-09-19 at 11 24 25 AM

**Comment by shadmansaleh** [comment]
tokyonight theme is working correctly for me.

Are you lazy loading lualine/tokyonight ? Is it garanteed tokyonight is loaded before lualine ?

Are you using neovim  nightly ? There was an issue #57 with theme loading there that already has been fixed.

I think it's a config issue.
Still can you bisect and find which commit broke it for you?

**Comment by abzcoding** [comment]
thank you for clarifying it, yes i'm on neovim head and yes i'm lazy loading it, let me make sure that tokyonight loads before lualine

**Pull request closed without merging**
