### PR TITLE
feat: pywal theme

### PR DESCRIPTION
**Pull request by mtoohey31**

### CODE REVIEW

**Comment by shadmansaleh** [comment]
THEMES.md is sorted alphabetically . Can you put the pywal theme after powerline_night ?

**Comment by mtoohey31** [comment]
Whoops, didn't realize that, fixed in e55ff0b!

**Comment by shadmansaleh** [comment]
Thanks for your contribution 💯.

**Comment by mtoohey31** [comment]
No problem, thanks for your help and suggestions!

**Pull request merged**
