### PR TITLE
Improve runtime file searching performance with neovim api

### PR DESCRIPTION
**Pull request by spindensity**
Neovim has native API `nvim_get_runtime_file`, we could simplify runtime file searching logic and improve its performance with the native API.

### CODE REVIEW

**Comment by spindensity** [comment]
I do know why the commit in the "Conversation" tab is a 404 page, try to close and reopen the pull request but have no luck, however, the "Commits" and "Files changed" tabs are OK.

**Comment by shadmansaleh** [comment]
Did you notice any performance improvements ?

vim/neovim uses shell for globing . This is slower then just plan checking stats.

> I do know why the commit in the "Conversation" tab is a 404 page

github issue . I think I'm seeing it since yesterday .

**Comment by spindensity** [comment]
> Did you notice any performance improvements ?
> 
> vim/neovim uses shell for globing . That was slower then just plan checking stats IIRC.

Yes, a slightly faster on my notebook. [src\nvim\api\vim.c:nvim_get_runtime_file](https://github.com/neovim/neovim/blob/490e09c6d81b9bf52eac7aa146e62b3da2d86579/src/nvim/api/vim.c#L773-L784) eventually calls [src\nvim\path.c:gen_expand_wildcards](https://github.com/neovim/neovim/blob/490e09c6d81b9bf52eac7aa146e62b3da2d86579/src/nvim/path.c#L1189:5), if the input pattern does not have special wildcards nor environment variables, neovim would not start a shell to do expanding. In this plugin, it seems no special wildcards or environment variables passed when searching file in runtime path.

**Comment by shadmansaleh** [comment]
In that case we should remove rtp_searcher and replace the calls to rtp_searcher with `nvim_get_runtime_file`.

**Comment by spindensity** [comment]
After some profiling, I found the performances of the two ways are equal roughly, there is no benefit from making change.

I would like to close the pull request now.

**Comment by shadmansaleh** [comment]
merged in 904f9df637c5d2768285ac3dc99caebea0c5c24e .

Sorry I messed up the authorship of the commit ;/

Thanks for the pr.

**Pull request closed without merging**
