### PR TITLE
feat: Add type option to hint what type of component is the string

### PR DESCRIPTION
**Pull request by shadmansaleh**
Because strings can mean many kinds of component lualine has to do lots of checks to figure out what user actually meant .

 This pr adds a new global option `type`. With that user can specify what they want as optimization.
When user doesn't provide type lualine will just do the checks like before .

Currently available types:
- module ( components like 'branch'/'diff' that are in &rtp/lua/lualine/components)
- builtin_items ( like %f, %m . These strings are directly sent in statusline and are handled by neovim . If you want to display some static string . You can use this type)
- variables&options ( like b:var/go:option . This could use a better name 😑)
- vim_function (vim function name like 'coc#status')
- lua_eval (lua expressions)

### CODE REVIEW

**Comment by shadmansaleh** [comment]
@clason Is this fine ?

**Comment by clason** [comment]
Can you give an example of how this would look in practice?

**Comment by shadmansaleh** [comment]
In practice no one will use this 😅

Only if someone wants to optimize or face edge case where one type of component is detected as different type then they can specify the type with that. Like if you did

```lua
lualine_c = {
    {'vim.b.gitsigns_status', type='lua_eval'}
}
```

Then lualine won't go checking if there's a file named vim.b.gitsigns_status.lua in rtp/lua/lualine/components. Thoigh that issue was only present for vim_function(without #) and lua_eval components as other cases would get rejected via file_name check.

**Comment by clason** [comment]
Thanks, it wasn't completely clear to me from the documentation. I think that's fine (as an advanced usage), _if_ you want to make the extra effort.

Only thing I'd bike-shed on is the name; I'd like them to be more concise; e.g.,
* 'var'/'opt'
* 'stl'
* 'mod'
* 'fun'
* 'lua'

(As you say, only the last three are really useful, so maybe support only those?)

An alternative I'd mention for the sake of completeness is to extend the `b:foo` syntax to the other types as well, so `m:foo` would be a module/extension, `f:foo` a vim function, `l:foo` a Lua function?

**Comment by shadmansaleh** [comment]
> Thanks, it wasn't completely clear to me from the documentation

Yeah documentation is scarce . There used to be a massive README it was kind of a mess . So it was replaced with a short hand version . I'll hopefully be able to write some wikis with details.

> Only thing I'd bike-shed on is the name; I'd like them to be more concise;

I was thinking of short or single letter aliases for the type names to make it simpler in config.

> As you say, only the last three are really useful, so maybe support only those

I think we should support full spectrum and don't try to guess when user provides a  type .

> so m:foo would be a module/extension, f:foo a vim function, l:foo a Lua function

I'd like to avoid this . Like I said in practice no one needs to specify types . Lualine does a good job at differentiating them . That's why I don't think this is enough reason to break everyones setup.

**Comment by clason** [comment]
> Yeah documentation is scarce . There used to be a massive README it was kind of a mess . So it was replaced with a short hand version . I'll hopefully be able to write some wikis with details.

Sure; I had assumed that docs is WIP (and especially something you want to postpone until fixing details).

> I was thinking of short or single letter aliases for the type names to make it simpler in config.

That also works, but I think three letters are a reasonable compromise.

> I think we should support full spectrum and don't try to guess when user provides a type .

Oh, for sure -- I just meant that (as you say) users should have no reason to provide a type for modules, options/variables and strings, since there the autodetection has no drawbacks?

But in general I agree: if you do this, better not to doc it partially.

> I'd like to avoid this . Like I said in practice no one needs to specify types . Lualine does a good job at differentiating them . That's why I don't think this is enough reason to break everyones setup.

Oh, I didn't mean to make it mandatory -- just _if_ the string starts with `f:`, short-circuit. 

But I just wanted to put the suggestion on the table.

**Comment by clason** [comment]
But maybe all that is overengineering, in the end. My actual issue was solved by realizing that `b:foo` is the proper _lualine_ syntax for variables as components, not literally including the _vimscript_ variable `b:foo`.

So I'd fine, too, if you just closed this.

**Comment by shadmansaleh** [comment]
> But maybe all that is overengineering, in the end

I'm merging this for now . As I can add newer types in the future . Then type option can make it easy to detect them.

**Pull request merged**
